import { ExerciseTemplate } from "./running";

function cycleMuscles(groups: string[]): ExerciseTemplate["muscles"] {
  const map: Record<string, ExerciseTemplate["muscles"][0]> = {
    "quads": { name: "Quadriceps", scientificName: "Quadriceps femoris", role: "primary", layer: "superficial", action: "Knee extension during downstroke (power phase)" },
    "hamstrings": { name: "Hamstrings", scientificName: "Biceps femoris group", role: "secondary", layer: "superficial", action: "Knee flexion during upstroke, hip extension" },
    "glutes": { name: "Gluteus Maximus", scientificName: "Gluteus maximus", role: "primary", layer: "superficial", action: "Hip extension during power phase" },
    "calves": { name: "Gastrocnemius", scientificName: "Gastrocnemius", role: "secondary", layer: "superficial", action: "Plantarflexion through pedal stroke" },
    "core": { name: "Core Complex", scientificName: "Rectus abdominis, Obliques, Erector spinae", role: "stabilizer", layer: "core", action: "Trunk stabilization and power transfer" },
    "hip flexors": { name: "Iliopsoas", scientificName: "Iliacus & Psoas major", role: "secondary", layer: "deep", action: "Hip flexion during upstroke" },
    "arms": { name: "Upper Body", scientificName: "Biceps, Triceps, Forearms", role: "stabilizer", layer: "superficial", action: "Handlebar control and climbing leverage" },
    "full body": { name: "Full Body", scientificName: "Multiple muscle groups", role: "primary", layer: "superficial", action: "Total body coordination" },
  };
  return groups.map(g => map[g] || { name: g, scientificName: g, role: "secondary" as const, layer: "superficial" as const, action: "Movement assistance" });
}

export const cyclingExercises: ExerciseTemplate[] = [
  { id: "cyc-endurance", name: "Endurance Ride", category: "cycling", subcategory: "endurance", description: "Steady zone 2 ride building aerobic base", muscleGroups: ["quads", "hamstrings", "glutes", "calves"], muscles: cycleMuscles(["quads", "hamstrings", "glutes", "calves"]), equipment: ["road bike"], difficulty: "beginner", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-long", name: "Long Ride", category: "cycling", subcategory: "endurance", description: "Extended distance ride for endurance adaptation", muscleGroups: ["quads", "hamstrings", "glutes", "calves", "core"], muscles: cycleMuscles(["quads", "hamstrings", "glutes", "calves", "core"]), equipment: ["road bike"], difficulty: "intermediate", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-vo2max", name: "VO2max Intervals", category: "cycling", subcategory: "intervals", description: "Hard 3-5 min efforts at 106-120% FTP", muscleGroups: ["quads", "hamstrings", "glutes"], muscles: cycleMuscles(["quads", "hamstrings", "glutes"]), equipment: ["bike"], difficulty: "advanced", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-threshold", name: "Threshold Intervals", category: "cycling", subcategory: "intervals", description: "Sustained efforts at 95-105% FTP", muscleGroups: ["quads", "hamstrings", "glutes"], muscles: cycleMuscles(["quads", "hamstrings", "glutes"]), equipment: ["bike"], difficulty: "advanced", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-sweetspot", name: "Sweet Spot Intervals", category: "cycling", subcategory: "intervals", description: "Efforts at 88-93% FTP for high stimulus with manageable fatigue", muscleGroups: ["quads", "hamstrings", "glutes"], muscles: cycleMuscles(["quads", "hamstrings", "glutes"]), equipment: ["bike"], difficulty: "intermediate", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-hill-repeats", name: "Hill Climb Repeats", category: "cycling", subcategory: "hill-climbing", description: "Repeated hard climbs on a steep gradient", muscleGroups: ["quads", "glutes", "calves", "core"], muscles: cycleMuscles(["quads", "glutes", "calves", "core"]), equipment: ["bike"], difficulty: "advanced", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-tt", name: "Time Trial Effort", category: "cycling", subcategory: "time-trial", description: "Sustained best effort over a set distance or time", muscleGroups: ["quads", "hamstrings", "glutes", "core"], muscles: cycleMuscles(["quads", "hamstrings", "glutes", "core"]), equipment: ["TT bike or road bike"], difficulty: "advanced", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-sprint", name: "Sprint Intervals", category: "cycling", subcategory: "intervals", description: "Short all-out sprints for neuromuscular power", muscleGroups: ["quads", "glutes", "calves"], muscles: cycleMuscles(["quads", "glutes", "calves"]), equipment: ["bike"], difficulty: "advanced", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "ballistic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-cadence-high", name: "High Cadence Drills", category: "cycling", subcategory: "cadence", description: "Spin at 100-120 rpm in easy gear for pedaling efficiency", muscleGroups: ["quads", "hip flexors", "calves"], muscles: cycleMuscles(["quads", "hip flexors", "calves"]), equipment: ["bike"], difficulty: "beginner", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-indoor", name: "Indoor Trainer Workout", category: "cycling", subcategory: "indoor", description: "Structured workout on smart trainer or rollers", muscleGroups: ["quads", "hamstrings", "glutes"], muscles: cycleMuscles(["quads", "hamstrings", "glutes"]), equipment: ["smart trainer"], difficulty: "beginner", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-tempo", name: "Tempo Ride", category: "cycling", subcategory: "endurance", description: "Sustained effort at 76-87% FTP, zone 3", muscleGroups: ["quads", "hamstrings", "glutes"], muscles: cycleMuscles(["quads", "hamstrings", "glutes"]), equipment: ["bike"], difficulty: "intermediate", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "cyc-recovery", name: "Recovery Ride", category: "cycling", subcategory: "recovery", description: "Very easy spin for active recovery", muscleGroups: ["quads", "hamstrings", "calves"], muscles: cycleMuscles(["quads", "hamstrings", "calves"]), equipment: ["bike"], difficulty: "beginner", movementPattern: "pedal-stroke", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
];

export const triathlonExercises: ExerciseTemplate[] = [
  { id: "tri-brick-bike-run", name: "Bike-to-Run Brick", category: "triathlon", subcategory: "brick", description: "Cycling immediately followed by running to adapt to transition", muscleGroups: ["quads", "hamstrings", "glutes", "calves"], muscles: cycleMuscles(["quads", "hamstrings", "glutes", "calves"]), equipment: ["bike", "running shoes"], difficulty: "intermediate", movementPattern: "multi-sport", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "tri-sprint-sim", name: "Sprint Triathlon Simulation", category: "triathlon", subcategory: "race-specific", description: "750m swim / 20km bike / 5km run at race pace", muscleGroups: ["full body"], muscles: cycleMuscles(["full body"]), equipment: ["full tri gear"], difficulty: "intermediate", movementPattern: "multi-sport", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "hip", "knee", "ankle"] },
  { id: "tri-olympic-sim", name: "Olympic Triathlon Simulation", category: "triathlon", subcategory: "race-specific", description: "1500m swim / 40km bike / 10km run at race pace", muscleGroups: ["full body"], muscles: cycleMuscles(["full body"]), equipment: ["full tri gear"], difficulty: "advanced", movementPattern: "multi-sport", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "hip", "knee", "ankle"] },
  { id: "tri-t1-practice", name: "T1 Transition Practice", category: "triathlon", subcategory: "transitions", description: "Drill swim exit, wetsuit removal, and bike mount", muscleGroups: ["full body"], muscles: cycleMuscles(["full body"]), equipment: ["wetsuit", "bike"], difficulty: "beginner", movementPattern: "transition", plane: "multi-planar", forceType: "dynamic", joints: ["full body"] },
  { id: "tri-t2-practice", name: "T2 Transition Practice", category: "triathlon", subcategory: "transitions", description: "Drill bike dismount, shoe change, and run start", muscleGroups: ["full body"], muscles: cycleMuscles(["full body"]), equipment: ["bike", "running shoes"], difficulty: "beginner", movementPattern: "transition", plane: "multi-planar", forceType: "dynamic", joints: ["full body"] },
];
