import { ExerciseTemplate } from "./running";

function simpleMuscles(groups: string[]): ExerciseTemplate["muscles"] {
  const map: Record<string, ExerciseTemplate["muscles"][0]> = {
    "lats": { name: "Latissimus Dorsi", scientificName: "Latissimus dorsi", role: "primary", layer: "superficial", action: "Shoulder extension and adduction" },
    "triceps": { name: "Triceps Brachii", scientificName: "Triceps brachii", role: "secondary", layer: "superficial", action: "Elbow extension" },
    "core": { name: "Core Complex", scientificName: "Rectus abdominis, Obliques, Transversus abdominis", role: "stabilizer", layer: "core", action: "Trunk stabilization" },
    "shoulders": { name: "Deltoid", scientificName: "Deltoideus", role: "primary", layer: "superficial", action: "Shoulder flexion/extension" },
    "quads": { name: "Quadriceps", scientificName: "Quadriceps femoris", role: "primary", layer: "superficial", action: "Knee extension" },
    "glutes": { name: "Gluteus Maximus", scientificName: "Gluteus maximus", role: "primary", layer: "superficial", action: "Hip extension" },
    "calves": { name: "Gastrocnemius", scientificName: "Gastrocnemius", role: "secondary", layer: "superficial", action: "Plantarflexion" },
    "hamstrings": { name: "Hamstrings", scientificName: "Biceps femoris group", role: "secondary", layer: "superficial", action: "Knee flexion, hip extension" },
    "back": { name: "Back Complex", scientificName: "Latissimus dorsi, Erector spinae, Rhomboids", role: "primary", layer: "superficial", action: "Spinal extension, pulling" },
    "biceps": { name: "Biceps Brachii", scientificName: "Biceps brachii", role: "secondary", layer: "superficial", action: "Elbow flexion" },
    "grip": { name: "Forearm Flexors", scientificName: "Flexor digitorum group", role: "primary", layer: "superficial", action: "Grip strength" },
    "traps": { name: "Trapezius", scientificName: "Trapezius", role: "secondary", layer: "superficial", action: "Scapular elevation and retraction" },
    "chest": { name: "Pectoralis Major", scientificName: "Pectoralis major", role: "primary", layer: "superficial", action: "Horizontal press, shoulder adduction" },
    "front delts": { name: "Anterior Deltoid", scientificName: "Deltoideus – pars clavicularis", role: "primary", layer: "superficial", action: "Shoulder flexion" },
    "full body": { name: "Full Body", scientificName: "Multiple muscle groups", role: "primary", layer: "superficial", action: "Total body coordination" },
    "hip flexors": { name: "Iliopsoas", scientificName: "Iliacus & Psoas major", role: "secondary", layer: "deep", action: "Hip flexion" },
    "legs": { name: "Lower Body", scientificName: "Quadriceps, Hamstrings, Glutes", role: "primary", layer: "superficial", action: "Lower body force production" },
    "arms": { name: "Arms", scientificName: "Biceps, Triceps", role: "secondary", layer: "superficial", action: "Upper body force" },
    "adductors": { name: "Hip Adductors", scientificName: "Adductor group", role: "secondary", layer: "deep", action: "Hip adduction" },
    "upper back": { name: "Upper Back", scientificName: "Trapezius, Rhomboids", role: "secondary", layer: "superficial", action: "Scapular retraction" },
    "lower back": { name: "Erector Spinae", scientificName: "Erector spinae", role: "stabilizer", layer: "deep", action: "Spinal extension" },
    "neck": { name: "Neck Muscles", scientificName: "Sternocleidomastoid, Scalenes", role: "stabilizer", layer: "superficial", action: "Head stabilization" },
  };
  return groups.map(g => map[g] || { name: g, scientificName: g, role: "secondary" as const, layer: "superficial" as const, action: "Movement assistance" });
}

export const hyroxExercises: ExerciseTemplate[] = [
  { id: "hyrox-ski-erg", name: "SkiErg", category: "hyrox", subcategory: "stations", description: "1000m ski erg — standing pull-down motion for upper body and core", muscleGroups: ["lats", "triceps", "core", "shoulders"], muscles: simpleMuscles(["lats", "triceps", "core", "shoulders"]), equipment: ["SkiErg"], difficulty: "intermediate", movementPattern: "vertical-pull", plane: "sagittal", forceType: "pull", joints: ["shoulder", "elbow", "spine"] },
  { id: "hyrox-sled-push", name: "Sled Push", category: "hyrox", subcategory: "stations", description: "50m heavy sled push for leg drive and conditioning", muscleGroups: ["quads", "glutes", "calves", "core"], muscles: simpleMuscles(["quads", "glutes", "calves", "core"]), equipment: ["sled"], difficulty: "advanced", movementPattern: "horizontal-push", plane: "sagittal", forceType: "push", joints: ["hip", "knee", "ankle"] },
  { id: "hyrox-sled-pull", name: "Sled Pull", category: "hyrox", subcategory: "stations", description: "50m sled pull using rope hand-over-hand", muscleGroups: ["back", "biceps", "grip", "core"], muscles: simpleMuscles(["back", "biceps", "grip", "core"]), equipment: ["sled", "rope"], difficulty: "advanced", movementPattern: "horizontal-pull", plane: "sagittal", forceType: "pull", joints: ["shoulder", "elbow"] },
  { id: "hyrox-burpee-broad-jump", name: "Burpee Broad Jump", category: "hyrox", subcategory: "stations", description: "80m of burpee broad jumps — full body explosive movement", muscleGroups: ["full body"], muscles: simpleMuscles(["full body"]), equipment: [], difficulty: "advanced", movementPattern: "plyometric", plane: "sagittal", forceType: "ballistic", joints: ["hip", "knee", "ankle", "shoulder"] },
  { id: "hyrox-rowing", name: "Rowing (HYROX)", category: "hyrox", subcategory: "stations", description: "1000m rowing station for full-body pulling", muscleGroups: ["back", "legs", "arms", "core"], muscles: simpleMuscles(["back", "legs", "arms", "core"]), equipment: ["rowing machine"], difficulty: "intermediate", movementPattern: "row-stroke", plane: "sagittal", forceType: "pull", joints: ["hip", "knee", "shoulder", "elbow"] },
  { id: "hyrox-farmers-carry", name: "Farmer's Carry (HYROX)", category: "hyrox", subcategory: "stations", description: "200m farmer's carry with kettlebells", muscleGroups: ["grip", "traps", "core", "legs"], muscles: simpleMuscles(["grip", "traps", "core", "legs"]), equipment: ["kettlebells"], difficulty: "intermediate", movementPattern: "carry", plane: "sagittal", forceType: "isometric", joints: ["grip", "spine"] },
  { id: "hyrox-wall-balls", name: "Wall Balls (HYROX)", category: "hyrox", subcategory: "stations", description: "100 reps of wall ball shots", muscleGroups: ["quads", "glutes", "shoulders", "core"], muscles: simpleMuscles(["quads", "glutes", "shoulders", "core"]), equipment: ["wall ball"], difficulty: "advanced", movementPattern: "squat-press", plane: "sagittal", forceType: "compound", joints: ["hip", "knee", "shoulder"] },
  { id: "hyrox-sandbag-lunge", name: "Sandbag Lunges", category: "hyrox", subcategory: "stations", description: "100m walking lunges with sandbag on shoulder", muscleGroups: ["quads", "glutes", "core"], muscles: simpleMuscles(["quads", "glutes", "core"]), equipment: ["sandbag"], difficulty: "advanced", movementPattern: "lunge", plane: "sagittal", forceType: "compound", joints: ["hip", "knee", "ankle"] },
];

export const crossfitExercises: ExerciseTemplate[] = [
  { id: "cf-pullup", name: "Kipping Pull-Up", category: "crossfit", subcategory: "gymnastics", description: "Dynamic pull-up using hip drive for high-rep sets", muscleGroups: ["lats", "biceps", "core"], muscles: simpleMuscles(["lats", "biceps", "core"]), equipment: ["pull-up bar"], difficulty: "intermediate", movementPattern: "vertical-pull", plane: "frontal", forceType: "pull", joints: ["shoulder", "elbow"] },
  { id: "cf-muscle-up", name: "Bar Muscle-Up", category: "crossfit", subcategory: "gymnastics", description: "Explosive pull-up transitioning over the bar", muscleGroups: ["lats", "chest", "triceps", "core"], muscles: simpleMuscles(["lats", "chest", "triceps", "core"]), equipment: ["pull-up bar"], difficulty: "elite", movementPattern: "pull-to-push", plane: "sagittal", forceType: "compound", joints: ["shoulder", "elbow"] },
  { id: "cf-hspu", name: "Handstand Push-Up", category: "crossfit", subcategory: "gymnastics", description: "Inverted pressing against wall or freestanding", muscleGroups: ["shoulders", "triceps", "core"], muscles: simpleMuscles(["shoulders", "triceps", "core"]), equipment: [], difficulty: "advanced", movementPattern: "vertical-press", plane: "sagittal", forceType: "push", joints: ["shoulder", "elbow"] },
  { id: "cf-toes-to-bar", name: "Toes-to-Bar", category: "crossfit", subcategory: "gymnastics", description: "Hanging, swing toes up to touch the bar", muscleGroups: ["core", "hip flexors", "lats"], muscles: simpleMuscles(["core", "hip flexors", "lats"]), equipment: ["pull-up bar"], difficulty: "intermediate", movementPattern: "hip-flexion", plane: "sagittal", forceType: "dynamic", joints: ["hip", "spine", "shoulder"] },
  { id: "cf-fran", name: "Fran", category: "crossfit", subcategory: "benchmark-wod", description: "21-15-9: Thrusters (43/30kg) and Pull-Ups", muscleGroups: ["full body"], muscles: simpleMuscles(["full body"]), equipment: ["barbell", "pull-up bar"], difficulty: "advanced", movementPattern: "mixed-modal", plane: "multi-planar", forceType: "compound", joints: ["hip", "knee", "shoulder", "elbow"] },
  { id: "cf-murph", name: "Murph", category: "crossfit", subcategory: "hero-wod", description: "1 mile run, 100 pull-ups, 200 push-ups, 300 squats, 1 mile run (20lb vest)", muscleGroups: ["full body"], muscles: simpleMuscles(["full body"]), equipment: ["pull-up bar", "weight vest"], difficulty: "elite", movementPattern: "mixed-modal", plane: "multi-planar", forceType: "compound", joints: ["full body"] },
  { id: "cf-thruster", name: "Thruster", category: "crossfit", subcategory: "movements", description: "Front squat into overhead press in one fluid motion", muscleGroups: ["quads", "glutes", "shoulders", "triceps", "core"], muscles: simpleMuscles(["quads", "glutes", "shoulders", "triceps", "core"]), equipment: ["barbell"], difficulty: "intermediate", movementPattern: "squat-press", plane: "sagittal", forceType: "compound", joints: ["hip", "knee", "shoulder", "elbow"] },
  { id: "cf-power-clean", name: "Power Clean", category: "crossfit", subcategory: "movements", description: "Explosive pull from floor to front rack without full squat", muscleGroups: ["full body"], muscles: simpleMuscles(["full body"]), equipment: ["barbell"], difficulty: "advanced", movementPattern: "olympic-pull", plane: "sagittal", forceType: "ballistic", joints: ["hip", "knee", "ankle", "shoulder", "elbow"] },
  { id: "cf-wall-ball", name: "Wall Ball Shot", category: "crossfit", subcategory: "movements", description: "Squat and throw medicine ball to target", muscleGroups: ["quads", "glutes", "shoulders", "core"], muscles: simpleMuscles(["quads", "glutes", "shoulders", "core"]), equipment: ["wall ball"], difficulty: "beginner", movementPattern: "squat-press", plane: "sagittal", forceType: "compound", joints: ["hip", "knee", "shoulder"] },
  { id: "cf-double-under", name: "Double-Unders", category: "crossfit", subcategory: "movements", description: "Jump rope passing under feet twice per jump", muscleGroups: ["calves", "shoulders", "core"], muscles: simpleMuscles(["calves", "shoulders", "core"]), equipment: ["speed rope"], difficulty: "intermediate", movementPattern: "plyometric", plane: "sagittal", forceType: "ballistic", joints: ["ankle", "wrist"] },
  { id: "cf-kb-swing", name: "Kettlebell Swing (American)", category: "crossfit", subcategory: "movements", description: "Full overhead kettlebell swing", muscleGroups: ["glutes", "hamstrings", "shoulders", "core"], muscles: simpleMuscles(["glutes", "hamstrings", "shoulders", "core"]), equipment: ["kettlebell"], difficulty: "intermediate", movementPattern: "hip-hinge", plane: "sagittal", forceType: "ballistic", joints: ["hip", "shoulder"] },
];

export const weightliftingExercises: ExerciseTemplate[] = [
  { id: "wl-snatch", name: "Snatch", category: "weightlifting", subcategory: "competition-lift", description: "Full squat snatch from floor to overhead in one motion", muscleGroups: ["full body"], muscles: simpleMuscles(["full body"]), equipment: ["barbell", "bumper plates"], difficulty: "elite", movementPattern: "olympic-pull", plane: "sagittal", forceType: "ballistic", joints: ["hip", "knee", "ankle", "shoulder", "elbow", "wrist"] },
  { id: "wl-clean-jerk", name: "Clean & Jerk", category: "weightlifting", subcategory: "competition-lift", description: "Clean to front rack then jerk overhead — the other competition lift", muscleGroups: ["full body"], muscles: simpleMuscles(["full body"]), equipment: ["barbell", "bumper plates"], difficulty: "elite", movementPattern: "olympic-pull", plane: "sagittal", forceType: "ballistic", joints: ["hip", "knee", "ankle", "shoulder", "elbow"] },
  { id: "wl-power-snatch", name: "Power Snatch", category: "weightlifting", subcategory: "snatch-variations", description: "Snatch caught in power position above parallel", muscleGroups: ["full body"], muscles: simpleMuscles(["full body"]), equipment: ["barbell"], difficulty: "advanced", movementPattern: "olympic-pull", plane: "sagittal", forceType: "ballistic", joints: ["hip", "knee", "shoulder"] },
  { id: "wl-overhead-squat", name: "Overhead Squat", category: "weightlifting", subcategory: "snatch-variations", description: "Full depth squat with barbell locked out overhead", muscleGroups: ["quads", "shoulders", "core", "upper back"], muscles: simpleMuscles(["quads", "shoulders", "core", "upper back"]), equipment: ["barbell"], difficulty: "advanced", movementPattern: "squat", plane: "sagittal", forceType: "compound", joints: ["hip", "knee", "ankle", "shoulder"] },
  { id: "wl-front-squat-wl", name: "Front Squat (Weightlifting)", category: "weightlifting", subcategory: "clean-variations", description: "Front squat with clean grip for positional strength", muscleGroups: ["quads", "glutes", "core", "upper back"], muscles: simpleMuscles(["quads", "glutes", "core", "upper back"]), equipment: ["barbell", "squat rack"], difficulty: "intermediate", movementPattern: "squat", plane: "sagittal", forceType: "compound", joints: ["hip", "knee", "ankle"] },
  { id: "wl-push-press", name: "Push Press", category: "weightlifting", subcategory: "jerk-variations", description: "Dip and drive press without re-bending knees", muscleGroups: ["shoulders", "triceps", "legs"], muscles: simpleMuscles(["shoulders", "triceps", "legs"]), equipment: ["barbell"], difficulty: "intermediate", movementPattern: "vertical-press", plane: "sagittal", forceType: "push", joints: ["shoulder", "elbow", "hip", "knee"] },
  { id: "wl-split-jerk", name: "Split Jerk", category: "weightlifting", subcategory: "jerk-variations", description: "Dip and drive catching in split stance — competition style", muscleGroups: ["shoulders", "triceps", "legs", "core"], muscles: simpleMuscles(["shoulders", "triceps", "legs", "core"]), equipment: ["barbell"], difficulty: "advanced", movementPattern: "jerk", plane: "sagittal", forceType: "ballistic", joints: ["shoulder", "elbow", "hip", "knee"] },
];

export const powerliftingExercises: ExerciseTemplate[] = [
  { id: "pl-back-squat", name: "Competition Back Squat", category: "powerlifting", subcategory: "squat", description: "Low bar back squat to competition depth (hip crease below knee)", muscleGroups: ["quads", "glutes", "hamstrings", "core"], muscles: simpleMuscles(["quads", "glutes", "hamstrings", "core"]), equipment: ["barbell", "squat rack", "belt"], difficulty: "advanced", movementPattern: "squat", plane: "sagittal", forceType: "compound", joints: ["hip", "knee", "ankle", "spine"] },
  { id: "pl-pause-squat", name: "Pause Squat", category: "powerlifting", subcategory: "squat", description: "Squat with 2-3 second pause in the hole to build bottom strength", muscleGroups: ["quads", "glutes", "hamstrings"], muscles: simpleMuscles(["quads", "glutes", "hamstrings"]), equipment: ["barbell", "squat rack"], difficulty: "advanced", movementPattern: "squat", plane: "sagittal", forceType: "compound", joints: ["hip", "knee"] },
  { id: "pl-comp-bench", name: "Competition Bench Press", category: "powerlifting", subcategory: "bench", description: "Bench press with pause on chest as in competition", muscleGroups: ["chest", "triceps", "front delts"], muscles: simpleMuscles(["chest", "triceps", "front delts"]), equipment: ["barbell", "bench"], difficulty: "advanced", movementPattern: "horizontal-press", plane: "sagittal", forceType: "push", joints: ["shoulder", "elbow"] },
  { id: "pl-close-grip-bench", name: "Close-Grip Bench Press", category: "powerlifting", subcategory: "bench", description: "Narrow grip bench targeting triceps for lockout strength", muscleGroups: ["triceps", "chest", "front delts"], muscles: simpleMuscles(["triceps", "chest", "front delts"]), equipment: ["barbell", "bench"], difficulty: "intermediate", movementPattern: "horizontal-press", plane: "sagittal", forceType: "push", joints: ["shoulder", "elbow"] },
  { id: "pl-conv-deadlift", name: "Conventional Deadlift (Competition)", category: "powerlifting", subcategory: "deadlift", description: "Competition style conventional deadlift", muscleGroups: ["back", "glutes", "hamstrings", "core", "grip"], muscles: simpleMuscles(["back", "glutes", "hamstrings", "core", "grip"]), equipment: ["barbell", "belt"], difficulty: "advanced", movementPattern: "hip-hinge", plane: "sagittal", forceType: "pull", joints: ["hip", "knee", "spine"] },
  { id: "pl-sumo-deadlift", name: "Sumo Deadlift", category: "powerlifting", subcategory: "deadlift", description: "Wide stance deadlift with hands inside knees", muscleGroups: ["quads", "glutes", "adductors", "back"], muscles: simpleMuscles(["quads", "glutes", "adductors", "back"]), equipment: ["barbell", "belt"], difficulty: "advanced", movementPattern: "hip-hinge", plane: "sagittal", forceType: "pull", joints: ["hip", "knee"] },
  { id: "pl-good-morning", name: "Good Morning", category: "powerlifting", subcategory: "accessories", description: "Barbell on back, hip hinge forward for posterior chain", muscleGroups: ["hamstrings", "glutes", "lower back"], muscles: simpleMuscles(["hamstrings", "glutes", "lower back"]), equipment: ["barbell"], difficulty: "intermediate", movementPattern: "hip-hinge", plane: "sagittal", forceType: "pull", joints: ["hip", "spine"] },
];
