export interface ExerciseTemplate {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  defaultSets?: number;
  defaultReps?: string;
  defaultDuration?: string;
  defaultDistance?: string;
  defaultRest?: string;
  defaultWeight?: string;
  muscleGroups: string[];
  equipment: string[];
  difficulty: "beginner" | "intermediate" | "advanced" | "elite";
}

export const runningExercises: ExerciseTemplate[] = [
  { id: "run-easy", name: "Easy Run", category: "running", subcategory: "endurance", description: "Low-intensity aerobic run at conversational pace", defaultDuration: "30-45 min", defaultDistance: "5-8 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "beginner" },
  { id: "run-recovery", name: "Recovery Run", category: "running", subcategory: "recovery", description: "Very easy effort to promote blood flow and recovery", defaultDuration: "20-30 min", defaultDistance: "3-5 km", muscleGroups: ["quads", "hamstrings", "calves"], equipment: [], difficulty: "beginner" },
  { id: "run-long", name: "Long Run", category: "running", subcategory: "endurance", description: "Extended distance run building aerobic base", defaultDuration: "60-150 min", defaultDistance: "15-30 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes", "core"], equipment: [], difficulty: "intermediate" },
  { id: "run-tempo", name: "Tempo Run", category: "running", subcategory: "threshold", description: "Sustained effort at lactate threshold pace", defaultDuration: "20-40 min", defaultDistance: "6-12 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-threshold", name: "Threshold Run", category: "running", subcategory: "threshold", description: "Running at or slightly below lactate threshold", defaultDuration: "20-30 min", defaultDistance: "5-10 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-progression", name: "Progression Run", category: "running", subcategory: "endurance", description: "Start easy and progressively increase pace each segment", defaultDuration: "40-60 min", defaultDistance: "8-14 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-fartlek", name: "Fartlek", category: "running", subcategory: "intervals", description: "Unstructured speed play mixing fast and slow segments", defaultDuration: "30-50 min", defaultDistance: "6-10 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-negative-split", name: "Negative Split Run", category: "running", subcategory: "endurance", description: "Run second half faster than the first half", defaultDuration: "40-60 min", defaultDistance: "8-14 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-100m-sprint", name: "100m Sprint", category: "running", subcategory: "sprints", description: "Maximum effort short sprint", defaultSets: 6, defaultReps: "1", defaultDistance: "100 m", defaultRest: "2-3 min", muscleGroups: ["quads", "hamstrings", "calves", "glutes", "hip flexors"], equipment: [], difficulty: "advanced" },
  { id: "run-200m-sprint", name: "200m Sprint", category: "running", subcategory: "sprints", description: "High-intensity sprint around the curve", defaultSets: 5, defaultReps: "1", defaultDistance: "200 m", defaultRest: "3-4 min", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-400m-sprint", name: "400m Sprint", category: "running", subcategory: "sprints", description: "Full lap sprint demanding anaerobic capacity", defaultSets: 4, defaultReps: "1", defaultDistance: "400 m", defaultRest: "4-5 min", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-800m-repeats", name: "800m Repeats", category: "running", subcategory: "intervals", description: "Half-mile repeats at VO2max pace", defaultSets: 6, defaultReps: "1", defaultDistance: "800 m", defaultRest: "2-3 min", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-mile-repeats", name: "Mile Repeats", category: "running", subcategory: "intervals", description: "One-mile repeats at threshold to VO2max pace", defaultSets: 4, defaultReps: "1", defaultDistance: "1600 m", defaultRest: "3-4 min", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-5k-intervals", name: "5K Pace Intervals", category: "running", subcategory: "intervals", description: "Intervals at current 5K race pace", defaultSets: 5, defaultReps: "1", defaultDistance: "1000 m", defaultRest: "2 min", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-10k-intervals", name: "10K Pace Intervals", category: "running", subcategory: "intervals", description: "Sustained intervals at 10K race pace", defaultSets: 4, defaultReps: "1", defaultDistance: "2000 m", defaultRest: "2-3 min", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-hill-sprints", name: "Hill Sprints", category: "running", subcategory: "hill-work", description: "Short maximal sprints up a steep hill", defaultSets: 8, defaultReps: "1", defaultDuration: "10-15 sec", defaultRest: "full recovery", muscleGroups: ["quads", "glutes", "calves", "hamstrings"], equipment: [], difficulty: "advanced" },
  { id: "run-hill-repeats", name: "Hill Repeats", category: "running", subcategory: "hill-work", description: "Longer hill efforts building strength endurance", defaultSets: 6, defaultReps: "1", defaultDuration: "60-90 sec", defaultRest: "jog down", muscleGroups: ["quads", "glutes", "calves", "hamstrings"], equipment: [], difficulty: "intermediate" },
  { id: "run-downhill-strides", name: "Downhill Strides", category: "running", subcategory: "hill-work", description: "Controlled fast running on a slight downhill to develop turnover", defaultSets: 6, defaultReps: "1", defaultDistance: "100 m", defaultRest: "walk back", muscleGroups: ["quads", "hamstrings", "calves"], equipment: [], difficulty: "intermediate" },
  { id: "run-hill-bounding", name: "Hill Bounding", category: "running", subcategory: "hill-work", description: "Exaggerated bounding strides uphill for power", defaultSets: 6, defaultReps: "1", defaultDistance: "60-80 m", defaultRest: "walk down", muscleGroups: ["glutes", "quads", "calves", "hip flexors"], equipment: [], difficulty: "advanced" },
  { id: "run-a-skip", name: "A-Skip Drill", category: "running", subcategory: "drills", description: "Skipping with high knee drive emphasizing posture", defaultSets: 3, defaultReps: "1", defaultDistance: "40 m", defaultRest: "walk back", muscleGroups: ["hip flexors", "calves", "core"], equipment: [], difficulty: "beginner" },
  { id: "run-b-skip", name: "B-Skip Drill", category: "running", subcategory: "drills", description: "A-skip with leg extension to develop hamstring pawback", defaultSets: 3, defaultReps: "1", defaultDistance: "40 m", defaultRest: "walk back", muscleGroups: ["hamstrings", "hip flexors", "calves"], equipment: [], difficulty: "beginner" },
  { id: "run-high-knees", name: "High Knees", category: "running", subcategory: "drills", description: "Rapid knee drive drill for turnover and hip flexor activation", defaultSets: 3, defaultReps: "1", defaultDuration: "20 sec", defaultRest: "30 sec", muscleGroups: ["hip flexors", "calves", "core"], equipment: [], difficulty: "beginner" },
  { id: "run-butt-kicks", name: "Butt Kicks", category: "running", subcategory: "drills", description: "Fast heel-to-glute drill for hamstring activation", defaultSets: 3, defaultReps: "1", defaultDuration: "20 sec", defaultRest: "30 sec", muscleGroups: ["hamstrings", "calves"], equipment: [], difficulty: "beginner" },
  { id: "run-carioca", name: "Carioca / Grapevine", category: "running", subcategory: "drills", description: "Lateral crossover drill for hip mobility and coordination", defaultSets: 3, defaultReps: "1", defaultDistance: "40 m", defaultRest: "walk back", muscleGroups: ["hip flexors", "adductors", "glutes"], equipment: [], difficulty: "beginner" },
  { id: "run-bounding", name: "Bounding", category: "running", subcategory: "drills", description: "Exaggerated running strides for power development", defaultSets: 4, defaultReps: "1", defaultDistance: "50 m", defaultRest: "walk back", muscleGroups: ["glutes", "quads", "calves"], equipment: [], difficulty: "intermediate" },
  { id: "run-strides", name: "Strides", category: "running", subcategory: "drills", description: "Smooth accelerations to near-sprint speed with deceleration", defaultSets: 6, defaultReps: "1", defaultDistance: "100 m", defaultRest: "walk back", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "beginner" },
  { id: "run-acceleration", name: "Acceleration Runs", category: "running", subcategory: "drills", description: "Gradual build-up from jog to full sprint", defaultSets: 4, defaultReps: "1", defaultDistance: "100-150 m", defaultRest: "walk back", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-yasso-800s", name: "Yasso 800s", category: "running", subcategory: "intervals", description: "800m repeats where time in minutes:seconds predicts marathon time in hours:minutes", defaultSets: 10, defaultReps: "1", defaultDistance: "800 m", defaultRest: "equal to effort", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-ladder", name: "Ladder Intervals", category: "running", subcategory: "intervals", description: "Ascending/descending distance ladder: 200-400-800-400-200", defaultSets: 1, defaultReps: "5 rungs", defaultDistance: "2000 m total", defaultRest: "equal to effort", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-cruise-intervals", name: "Cruise Intervals", category: "running", subcategory: "threshold", description: "Threshold-pace repeats with short rest, popularized by Jack Daniels", defaultSets: 4, defaultReps: "1", defaultDistance: "1600 m", defaultRest: "60 sec", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-cutdown", name: "Cut-Down Run", category: "running", subcategory: "endurance", description: "Each mile or km faster than the previous one", defaultDuration: "30-50 min", defaultDistance: "8-12 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-marathon-pace", name: "Marathon Pace Run", category: "running", subcategory: "race-specific", description: "Sustained running at goal marathon pace", defaultDuration: "45-90 min", defaultDistance: "12-25 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes", "core"], equipment: [], difficulty: "advanced" },
  { id: "run-half-marathon-pace", name: "Half Marathon Pace Run", category: "running", subcategory: "race-specific", description: "Sustained running at goal half marathon pace", defaultDuration: "30-60 min", defaultDistance: "8-16 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-race-sim", name: "Race Simulation", category: "running", subcategory: "race-specific", description: "Full dress rehearsal at race pace with race nutrition", defaultDuration: "60-120 min", defaultDistance: "race distance", muscleGroups: ["quads", "hamstrings", "calves", "glutes", "core"], equipment: [], difficulty: "elite" },
  { id: "run-time-trial", name: "Time Trial", category: "running", subcategory: "race-specific", description: "All-out effort over a set distance for benchmarking", defaultSets: 1, defaultReps: "1", defaultDistance: "5 km", defaultRest: "none", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-treadmill-intervals", name: "Treadmill Intervals", category: "running", subcategory: "intervals", description: "Speed intervals on treadmill with incline variations", defaultSets: 8, defaultReps: "1", defaultDuration: "2 min on / 1 min off", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: ["treadmill"], difficulty: "intermediate" },
  { id: "run-track-repeats", name: "Track Repeats", category: "running", subcategory: "intervals", description: "Structured repeats on a 400m track", defaultSets: 8, defaultReps: "1", defaultDistance: "400 m", defaultRest: "90 sec", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-vo2max", name: "VO2max Intervals", category: "running", subcategory: "intervals", description: "Hard efforts at 95-100% VO2max to boost oxygen uptake", defaultSets: 5, defaultReps: "1", defaultDuration: "3-5 min", defaultRest: "equal to effort", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "elite" },
  { id: "run-tabata", name: "Tabata Sprints", category: "running", subcategory: "sprints", description: "20 sec max sprint / 10 sec rest x 8 rounds", defaultSets: 8, defaultReps: "1", defaultDuration: "20 sec", defaultRest: "10 sec", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "advanced" },
  { id: "run-walk-intervals", name: "Run/Walk Intervals", category: "running", subcategory: "endurance", description: "Alternating running and walking segments for beginners or ultra prep", defaultSets: 10, defaultReps: "1", defaultDuration: "4 min run / 1 min walk", muscleGroups: ["quads", "hamstrings", "calves"], equipment: [], difficulty: "beginner" },
  { id: "run-trail", name: "Trail Run", category: "running", subcategory: "endurance", description: "Off-road running on varied terrain", defaultDuration: "45-90 min", defaultDistance: "8-15 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes", "ankles", "core"], equipment: ["trail shoes"], difficulty: "intermediate" },
  { id: "run-beach", name: "Beach / Sand Run", category: "running", subcategory: "endurance", description: "Running on soft sand for added resistance", defaultDuration: "20-40 min", defaultDistance: "3-6 km", muscleGroups: ["calves", "quads", "glutes", "ankles"], equipment: [], difficulty: "intermediate" },
  { id: "run-parkrun", name: "Parkrun 5K", category: "running", subcategory: "race-specific", description: "Community 5K time trial effort", defaultSets: 1, defaultReps: "1", defaultDistance: "5 km", muscleGroups: ["quads", "hamstrings", "calves", "glutes"], equipment: [], difficulty: "intermediate" },
  { id: "run-straight-leg-shuffle", name: "Straight-Leg Shuffle", category: "running", subcategory: "drills", description: "Stiff-legged running drill focusing on ground contact", defaultSets: 3, defaultReps: "1", defaultDistance: "30 m", defaultRest: "walk back", muscleGroups: ["calves", "hamstrings", "hip flexors"], equipment: [], difficulty: "beginner" },
  { id: "run-ankling", name: "Ankling Drill", category: "running", subcategory: "drills", description: "Minimal forward movement focusing on ankle dorsiflexion and quick ground contact", defaultSets: 3, defaultReps: "1", defaultDistance: "30 m", defaultRest: "walk back", muscleGroups: ["calves", "ankles"], equipment: [], difficulty: "beginner" },
];
