import { ExerciseTemplate } from "./running";

// Helper to create basic muscle entries for swimming exercises
function swimMuscles(groups: string[]): ExerciseTemplate["muscles"] {
  const map: Record<string, ExerciseTemplate["muscles"][0]> = {
    "lats": { name: "Latissimus Dorsi", scientificName: "Latissimus dorsi", role: "primary", layer: "superficial", action: "Shoulder extension and adduction during pull phase" },
    "shoulders": { name: "Deltoid", scientificName: "Deltoideus", role: "primary", layer: "superficial", action: "Shoulder flexion/extension during stroke recovery" },
    "triceps": { name: "Triceps Brachii", scientificName: "Triceps brachii", role: "secondary", layer: "superficial", action: "Elbow extension during push phase" },
    "core": { name: "Core Complex", scientificName: "Rectus abdominis, Obliques, Transversus abdominis", role: "stabilizer", layer: "core", action: "Body rotation and streamline stabilization" },
    "chest": { name: "Pectoralis Major", scientificName: "Pectoralis major", role: "primary", layer: "superficial", action: "Shoulder adduction during pull" },
    "adductors": { name: "Hip Adductors", scientificName: "Adductor group", role: "primary", layer: "deep", action: "Leg squeeze during breaststroke kick" },
    "glutes": { name: "Gluteus Maximus", scientificName: "Gluteus maximus", role: "secondary", layer: "superficial", action: "Hip extension during kick" },
    "quads": { name: "Quadriceps", scientificName: "Quadriceps femoris", role: "primary", layer: "superficial", action: "Knee extension during kick" },
    "calves": { name: "Gastrocnemius", scientificName: "Gastrocnemius", role: "secondary", layer: "superficial", action: "Plantarflexion during flutter kick" },
    "hip flexors": { name: "Iliopsoas", scientificName: "Iliacus & Psoas major", role: "primary", layer: "deep", action: "Hip flexion during kick recovery" },
    "forearms": { name: "Forearm Flexors", scientificName: "Flexor digitorum group", role: "secondary", layer: "superficial", action: "Wrist stabilization and water grip" },
    "neck": { name: "Sternocleidomastoid", scientificName: "Sternocleidomastoideus", role: "secondary", layer: "superficial", action: "Head positioning for sighting and breathing" },
    "full body": { name: "Full Body", scientificName: "Multiple muscle groups", role: "primary", layer: "superficial", action: "Coordinated total body movement" },
    "biceps": { name: "Biceps Brachii", scientificName: "Biceps brachii", role: "secondary", layer: "superficial", action: "Elbow flexion during catch phase" },
  };
  return groups.map(g => map[g] || { name: g, scientificName: g, role: "secondary" as const, layer: "superficial" as const, action: "Movement assistance" });
}

export const swimmingExercises: ExerciseTemplate[] = [
  { id: "swim-free-endurance", name: "Freestyle Endurance", category: "swimming", subcategory: "freestyle", description: "Continuous freestyle at steady aerobic pace", muscleGroups: ["lats", "shoulders", "triceps", "core"], muscles: swimMuscles(["lats", "shoulders", "triceps", "core"]), equipment: [], difficulty: "beginner", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow", "hip", "knee"] },
  { id: "swim-free-sprint", name: "Freestyle Sprint", category: "swimming", subcategory: "freestyle", description: "Maximum effort freestyle over short distance", muscleGroups: ["lats", "shoulders", "triceps", "core"], muscles: swimMuscles(["lats", "shoulders", "triceps", "core"]), equipment: [], difficulty: "advanced", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "ballistic", joints: ["shoulder", "elbow", "hip"] },
  { id: "swim-free-intervals", name: "Freestyle Intervals", category: "swimming", subcategory: "freestyle", description: "Structured freestyle repeats at threshold pace", muscleGroups: ["lats", "shoulders", "triceps", "core"], muscles: swimMuscles(["lats", "shoulders", "triceps", "core"]), equipment: [], difficulty: "intermediate", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow", "hip"] },
  { id: "swim-back-endurance", name: "Backstroke Endurance", category: "swimming", subcategory: "backstroke", description: "Continuous backstroke at steady pace", muscleGroups: ["lats", "shoulders", "triceps", "core"], muscles: swimMuscles(["lats", "shoulders", "triceps", "core"]), equipment: [], difficulty: "intermediate", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow", "hip"] },
  { id: "swim-breast-endurance", name: "Breaststroke Endurance", category: "swimming", subcategory: "breaststroke", description: "Continuous breaststroke at moderate pace", muscleGroups: ["chest", "shoulders", "adductors", "glutes"], muscles: swimMuscles(["chest", "shoulders", "adductors", "glutes"]), equipment: [], difficulty: "intermediate", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "hip", "knee"] },
  { id: "swim-fly-sprint", name: "Butterfly Sprint", category: "swimming", subcategory: "butterfly", description: "Short explosive butterfly efforts", muscleGroups: ["lats", "shoulders", "chest", "core", "triceps"], muscles: swimMuscles(["lats", "shoulders", "chest", "core", "triceps"]), equipment: [], difficulty: "advanced", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "ballistic", joints: ["shoulder", "spine", "hip"] },
  { id: "swim-im", name: "Individual Medley (IM)", category: "swimming", subcategory: "IM", description: "Fly-Back-Breast-Free in sequence", muscleGroups: ["full body"], muscles: swimMuscles(["full body"]), equipment: [], difficulty: "advanced", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow", "hip", "knee"] },
  { id: "swim-kick-board", name: "Kick Set (Board)", category: "swimming", subcategory: "kick-sets", description: "Flutter kick with kickboard for leg endurance", muscleGroups: ["quads", "calves", "hip flexors", "core"], muscles: swimMuscles(["quads", "calves", "hip flexors", "core"]), equipment: ["kickboard"], difficulty: "beginner", movementPattern: "kick", plane: "sagittal", forceType: "dynamic", joints: ["hip", "knee", "ankle"] },
  { id: "swim-pull-buoy", name: "Pull Set (Buoy)", category: "swimming", subcategory: "pull-sets", description: "Freestyle pull with buoy between legs isolating upper body", muscleGroups: ["lats", "shoulders", "triceps"], muscles: swimMuscles(["lats", "shoulders", "triceps"]), equipment: ["pull buoy"], difficulty: "beginner", movementPattern: "swim-pull", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow"] },
  { id: "swim-ow-endurance", name: "Open Water Endurance", category: "swimming", subcategory: "open-water", description: "Continuous open water swim at steady pace", muscleGroups: ["full body"], muscles: swimMuscles(["full body"]), equipment: ["wetsuit", "goggles"], difficulty: "intermediate", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow", "hip", "knee"] },
  { id: "swim-fingertip-drag", name: "Fingertip Drag Drill", category: "swimming", subcategory: "drills", description: "Drag fingertips along water surface during recovery for high elbow", muscleGroups: ["shoulders", "lats"], muscles: swimMuscles(["shoulders", "lats"]), equipment: [], difficulty: "beginner", movementPattern: "drill", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow"] },
  { id: "swim-sculling", name: "Sculling Drill", category: "swimming", subcategory: "drills", description: "Small hand movements to develop water feel and catch awareness", muscleGroups: ["forearms", "shoulders"], muscles: swimMuscles(["forearms", "shoulders"]), equipment: [], difficulty: "beginner", movementPattern: "drill", plane: "transverse", forceType: "dynamic", joints: ["shoulder", "wrist"] },
  { id: "swim-threshold", name: "Threshold Set", category: "swimming", subcategory: "freestyle", description: "Sustained efforts at CSS (Critical Swim Speed) pace", muscleGroups: ["lats", "shoulders", "core"], muscles: swimMuscles(["lats", "shoulders", "core"]), equipment: [], difficulty: "advanced", movementPattern: "swim-stroke", plane: "multi-planar", forceType: "dynamic", joints: ["shoulder", "elbow", "hip"] },
  { id: "swim-dolphin-kick", name: "Dolphin Kick Set", category: "swimming", subcategory: "kick-sets", description: "Underwater dolphin kick on front or back", muscleGroups: ["core", "glutes", "quads"], muscles: swimMuscles(["core", "glutes", "quads"]), equipment: [], difficulty: "intermediate", movementPattern: "kick", plane: "sagittal", forceType: "dynamic", joints: ["spine", "hip", "knee"] },
];
